name: video_box
description: A control that plays video in flutter, I make the control as flexible as possible, can play a single video, video list on the page.
version: 0.18.0
homepage: https://github.com/januwA/flutter_video_box

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  connectivity_plus: ^6.1.4 
  sensors_plus: ^6.1.1 
  dart_printf: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

# flutter: